"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-24

The seven tables the application needs — ``users``, ``verifications``,
``verification_desks``, ``desk_reports``, ``claims``, ``sources`` and ``evidence`` —
written by hand rather than autogenerated because there was no database to
autogenerate against. The enum columns are ``VARCHAR`` + ``CHECK``
(``native_enum=False``) for the reason given in
:func:`app.models.types.enum_column`: adding a determination stays an ordinary
migration instead of an ``ALTER TYPE``.

JSON columns are declared with the PostgreSQL ``JSONB`` variant, matching
:func:`app.models.types.json_column`.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ID = sa.String(36)

DESK = sa.Enum(
    "text",
    "image",
    "fact-check",
    "decision",
    name="desk",
    native_enum=False,
)
FAILURE_DESK = sa.Enum(
    "text",
    "image",
    "fact-check",
    "decision",
    name="failure_desk",
    native_enum=False,
)
ARTIFACT_KIND = sa.Enum(
    "text",
    "claim",
    "url",
    "image",
    name="artifact_kind",
    native_enum=False,
)
DETERMINATION = sa.Enum(
    "SUPPORTED",
    "CONSISTENT",
    "CLEAR",
    "REQUIRES VERIFICATION",
    "INSUFFICIENT",
    "CONTESTED",
    "CONTRADICTED",
    "ANOMALOUS",
    "SYNTHETIC",
    name="determination",
    native_enum=False,
)
STATUS = sa.Enum(
    "pending", "running", "completed", "failed", name="status", native_enum=False
)
DATE_BASIS = sa.Enum(
    "provider",
    "provider_modified",
    "provider_relative",
    "url_path",
    name="date_basis",
    native_enum=False,
)


def _json() -> sa.types.TypeEngine[object]:
    return sa.JSON().with_variant(JSONB(), "postgresql")


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", ID, nullable=False),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("display_name", sa.String(120), nullable=False),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )

    op.create_table(
        "verifications",
        sa.Column("id", ID, nullable=False),
        sa.Column("user_id", ID, nullable=True),
        sa.Column("artifact_kind", ARTIFACT_KIND, nullable=False),
        sa.Column("artifact_content", sa.Text(), nullable=True),
        sa.Column("artifact_url", sa.Text(), nullable=True),
        sa.Column("artifact_filename", sa.String(255), nullable=True),
        sa.Column("status", STATUS, nullable=False),
        sa.Column("failure_code", sa.String(80), nullable=True),
        sa.Column("failure_message", sa.Text(), nullable=True),
        sa.Column("failure_desk", FAILURE_DESK, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_verifications"),
        # SET NULL, not CASCADE: closing an account must not delete the record of
        # what it had examined. See `app.domain.user.User.deactivated`.
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_verifications_user_id_users",
            ondelete="SET NULL",
        ),
    )

    op.create_table(
        "verification_desks",
        sa.Column("verification_id", ID, nullable=False),
        sa.Column("desk", DESK, nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("status", STATUS, nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint(
            "verification_id", "desk", name="pk_verification_desks"
        ),
        sa.ForeignKeyConstraint(
            ["verification_id"],
            ["verifications.id"],
            name="fk_verification_desks_verification_id_verifications",
            ondelete="CASCADE",
        ),
    )

    op.create_table(
        "desk_reports",
        sa.Column("id", ID, nullable=False),
        sa.Column("verification_id", ID, nullable=False),
        sa.Column("desk", DESK, nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("determination", DETERMINATION, nullable=False),
        sa.Column("headline", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("ledger", _json(), nullable=False),
        sa.Column("annotations", _json(), nullable=False),
        sa.Column("signals", _json(), nullable=False),
        sa.Column("exhibits", _json(), nullable=False),
        sa.Column("detail", _json(), nullable=True),
        sa.Column("filed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_desk_reports"),
        # No unique (verification_id, desk). The in-memory store accepts more than
        # one report from a desk, and the two implementations of the same Protocol
        # must agree on what is storable or swapping them changes behaviour.
        sa.ForeignKeyConstraint(
            ["verification_id"],
            ["verifications.id"],
            name="fk_desk_reports_verification_id_verifications",
            ondelete="CASCADE",
        ),
    )

    op.create_table(
        "claims",
        sa.Column("id", ID, nullable=False),
        sa.Column("verification_id", ID, nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("queries", _json(), nullable=False),
        sa.Column("fact_checks", _json(), nullable=False),
        sa.Column("researched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_claims"),
        sa.ForeignKeyConstraint(
            ["verification_id"],
            ["verifications.id"],
            name="fk_claims_verification_id_verifications",
            ondelete="CASCADE",
        ),
    )

    op.create_table(
        "sources",
        sa.Column("id", ID, nullable=False),
        sa.Column("claim_id", ID, nullable=False),
        sa.Column("ref", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("urls", _json(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("domain", sa.String(255), nullable=False),
        sa.Column("host", sa.String(255), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("date_basis", DATE_BASIS, nullable=True),
        sa.Column("date_text", sa.String(255), nullable=True),
        sa.Column("cluster", sa.Integer(), nullable=True),
        sa.Column("retrievals", _json(), nullable=False),
        sa.Column("credibility", _json(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_sources"),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
            name="fk_sources_claim_id_claims",
            ondelete="CASCADE",
        ),
    )

    op.create_table(
        "evidence",
        sa.Column("id", ID, nullable=False),
        sa.Column("source_id", ID, nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(60), nullable=False),
        # `end` is reserved in PostgreSQL; the domain's `start`/`end` are stored
        # under these names. See `app.models.research.EvidenceRow`.
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("matched_entities", _json(), nullable=False),
        sa.Column("matched_terms", _json(), nullable=False),
        sa.Column("matched_numbers", _json(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_evidence"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name="fk_evidence_source_id_sources",
            ondelete="CASCADE",
        ),
    )

    op.create_index("ix_verifications_user_id", "verifications", ["user_id"])
    op.create_index("ix_claims_verification_id", "claims", ["verification_id"])
    op.create_index("ix_sources_claim_id", "sources", ["claim_id"])
    op.create_index("ix_sources_domain", "sources", ["domain"])
    op.create_index("ix_evidence_source_id", "evidence", ["source_id"])


def downgrade() -> None:
    # Children before parents: the foreign keys cascade on delete, not on drop.
    op.drop_table("evidence")
    op.drop_table("sources")
    op.drop_table("claims")
    op.drop_table("desk_reports")
    op.drop_table("verification_desks")
    op.drop_table("verifications")
    op.drop_table("users")
