"""Declarative base for the ORM.

The naming convention is set here rather than left to SQLAlchemy's defaults
because Alembic generates constraint names from it. Without an explicit
convention, autogenerated migrations produce unnamed constraints that later
cannot be dropped by name, which turns a routine schema change into a manual one.
"""

from __future__ import annotations

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

#: Deterministic constraint names. `%(column_0_N_label)s` keeps names inside
#: PostgreSQL's 63-character identifier limit for multi-column constraints.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_N_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for every mapped model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
